#!/usr/bin/env bash

set -e

# read host
read -p "server (i.e example.com): " host
host=deploy@${host}

# read port
read -p "ssh port [default=22]: " port
port=${port:-22}

# manifest file
read -p "manifest file path [default=./manifest.pp]: " manifest
manifest=${manifest:-./manifest.pp}

# hiera data
read -p "secret hiera data [default=manifest.yaml]: " data

hiera="
---
:logger: console

:backends:
  - yaml

:hierarchy:
  - manifest

:yaml:
  :datadir: '.'"

scp -P $port $manifest $host:/tmp/manifest.pp
if [ -f "$data" ]; then
  scp -P $port $data     $host:/tmp/manifest.yaml
fi
ssh $host -p $port "echo \"$hiera\" > /tmp/hiera.yaml"
ssh $host -t -p $port 'cd /tmp && sudo puppet apply manifest.pp --hiera_config=hiera.yaml'

echo "All done!"
