backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/posts'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{year}}-{{month}}-{{day}}-{{title}}/{{slug}}'
    preview_path: blog/posts/{{path}}
    fields:
      - { label: 'Highlight', name: 'highlight', widget: 'boolean', default: true }
      - label: 'Path'
        name: 'path'
        widget: 'string'
        pattern: ['^[\d\w-_]+$', "You can only use letter, numbers, _ or -"]
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: "Categories"
        name: 'categories'
        widget: 'select'
        multiple: true
        options:
          - { value: 'case-studies', label: 'Case Studies' }
          - { value: 'engineering', label: 'Engineering' }
          - { value: 'design', label: 'Design' }
          - { value: 'product', label: 'Product' }
          - { value: 'research', label: 'Research' }
          - { value: 'inside-subvisual', label: 'Inside Subvisual' }
          - { value: 'academy', label: 'Academy' }
          - { value: 'company-building', label: 'Company Building' }
      - label: 'Author'
        name: 'author'
        widget: 'select'
        options:
          - 'alex-mendes'
          - 'alvaro-bezerra'
          - 'davide-silva'
          - 'fernando-mendes'
          - 'francisco-baila'
          - 'gabriel-poca'
          - 'joana-gomes'
          - 'joao-ferreira'
          - 'joao-justo'
          - 'jose-pedro-cabrita'
          - 'laura-esteves'
          - 'luis-zamith'
          - 'miguel-palhas'
          - 'mirha-masala'
          - 'nuno-reis'
          - 'pedro-costa'
          - 'pedro-oliveira'
          - 'roberto-machado'
          - 'ronaldo-sousa'
          - 'subvisual'
          - 'summer-campers'
      - { label: 'Publish Date', name: 'date', widget: 'date', format: 'YYYY-MM-DD' }
      - { label: 'Cover', name: 'cover', widget: 'image', allow_multiple: false, required: false }
      - { label: 'Social Media Cover', name: 'seoImage', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Intro', name: 'intro', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
