// Configure the Web app manifest generated by GatsbyJS.
//
// See https://developer.mozilla.org/en-US/docs/Web/Manifest for more
// information on Web app manifests.

const path = require("path")

module.exports = (root) => [
  {
    resolve: "gatsby-plugin-manifest",
    options: {
      background_color: "#fcfcfc",
      categories: ["business"],
      icon: path.resolve(root, "src/images/subvisual-symbol-blue.svg"),
      lang: "en",
      name: "Subvisual",
      short_name: "Subvisual",
      start_url: "/",
      theme_color: "#045cfc",
    },
  },
  {
    resolve: "gatsby-plugin-offline",
    options: {
      appendScript: path.resolve(root, "src/sw.js"),
    },
  },
]
